Implementación
IslasGECI/metadata_tools pull request #2
Opened 2020-07-15 17:58 UTC by nepito

# [Requisitos](https://github.com/IslasGECI/manual#implementaci%C3%B3n-en-python)
- [ ] Evoca mutantes de Python con Mutmut en GitHub Actions
- [ ] Corre una prueba dummy con Pytest en GitHub Actions
- [ ] Evalúa cambio de cobertura con Codecov en GitHub Actions
- [ ] Verifica formato de Python con Black en GitHub Actions
- [ ] Agrega phony lint a Makefile para correr Flake8 y Pylint (localmente, no en GitHub Actions)

2020-08-04 19:54 UTC, islasfernando approved these changes
Pues el calentamiento ya está

2020-08-06 16:57 UTC, devarops requested changes
Aqui dejo mi primer revisión.

2020-08-06 16:57 UTC, evaristor commented on metadatatools/Metadata/_DataVariable.py
> +
¿Seguirá funcionando sin pandas?
```suggestion
```

2020-08-06 16:57 UTC, evaristor commented on metadatatools/__init__.py
> +_version = "0.1.2"
¿Usamos esto? ¿No va en mayúsculas por ser constante?

2020-08-06 16:57 UTC, evaristor commented on est_getNamesFromAxis.py
> +import unittest
Parece que este archivo no va aquí en la raiz. Pareciera un error de dedo, en lugar de `est_getNamesFromAxis.py` debería ser `tests/test_getNamesFromAxis.py`?

2021-02-05 21:20 UTC, nepito commented on metadatatools/__init__.py
> +_version = "0.1.2"
Creo que aplicamos fernandiña

2021-02-05 21:27 UTC, nepito commented on est_getNamesFromAxis.py
> +import unittest
En el commit `d3bc03c466b0f7e0ad4388257f2c63102f535bed` corregimos esto. Y borramos ese archivo en el commit `187069e508e1e2bab9c5d1fb6d1d53b36cce568a` porque utilizaba `toolboxes` supongo que ahorita no está funcionando.

2021-03-04 23:41 UTC, xwalls commented
problema con archivos temporales por falta de .gitignore #6

2021-03-04 23:45 UTC, xwalls commented
falta documentación de la clase DataTable en el archivo _Tablanal.py_

2021-03-04 23:49 UTC, xwalls commented
recomiendo refactorizar el nombre de las variables
`diccionario`
y
`Campo`

pueden no ser muy claras

2021-04-05 21:34 UTC, evaristor commented on metadatatools/_StandardName.py
> +    catches = auto()
```suggestion
    number_of_captures = auto()
```

2021-04-16 16:33 UTC, merged